#ifndef __MULTIFURCATION_VERSION_HPP__
#define __MULTIFURCATION_VERSION_HPP__

#define MULTIFURCATION_VERSION_MAJOR 0
#define MULTIFURCATION_VERSION_MINOR 0
#define MULTIFURCATION_VERSION_PATCH 0

#endif // !__MULTIFURCATION_VERSION_HPP__